import "./globals.css";
import { Poppins } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

const poppin = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Blog Magazine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppin.className} flex flex-col min-h-screen`}>
        <NextTopLoader color="#16A34A" />
        {children}
      </body>
    </html>
  );
}
